In [175]:
from IPython.display import HTML
import plotly.express as px
import numpy as np
import cufflinks
cufflinks.go_offline()
cufflinks.set_config_file(world_readable=True, theme='pearl')
import plotly.graph_objs as go
import pandas as pd
import matplotlib.pyplot as plt

df = px.data.iris().iloc[:100,:].sample(n = 18)
fig = px.scatter(df, x="sepal_length", y="sepal_width", color="species",template="plotly_dark")
HTML(fig.to_html())

Output hidden; open in https://colab.research.google.com to view.

In [176]:
X_data=df.iloc[:,[0,1]]
Y_data=[y if y==1 else -1 for y in df.iloc[:100,-1]]

In [115]:
def sign(weights,x):
    x_new=np.append(x,1)
    return 1 if np.dot(weights,x_new)>0 else -1

In [116]:
def perceptron_update(weights,x,y):
    if sign(weights,x)!=y:
        weights = weights+ y*np.append(x,1)
    return weights

In [118]:
def error(weights, feature_set, labels):
    count=0
    for i in range(len(feature_set)):
        if sign(weights,feature_set[i])!=labels[i]:
            count=count+1
        else:
            count=count+0
    return count

In [106]:
def perceptron_learning_algorithm(num,feature_set,labels,e):
    count=50000
    feature_set=feature_set.values.tolist()
    weights=np.random.rand(num)
    error_measures=[]
    error_measures.append(error(weights,feature_set,labels))
    
    weight_vector=[]
    weight=[]
    
    while error(weights,feature_set,labels)>e:
        count=count-1
        for i in range(len(feature_set)):
            weights=perceptron_update(weights,feature_set[i],labels[i])
        weight_vector.append(weights)
        error_measures.append(error(weights,feature_set,labels))
        
        if count==0:
            break
            
    return weights,weight_vector,error_measures

In [177]:
w,W, error_points= perceptron_learning_algorithm(3,X_data, Y_data,0)

In [156]:
w

array([-2.43615042,  3.91357173,  0.77136471])

In [178]:
W

[array([4.24561635, 4.152823  , 1.66744774]),
 array([-1.05438365,  6.152823  ,  1.66744774]),
 array([-4.05438365,  8.252823  ,  1.66744774]),
 array([-5.15438365,  8.452823  ,  1.66744774])]

In [122]:
W[0][0]

-6.504844011927399

In [123]:
x_setosa=df[df.iloc[:,-1]==1].iloc[:,[0,1]]
x_versicolor=df[df.iloc[:,-1]==2].iloc[:,[0,1]]
x_setosa.iloc[:,0].values.tolist()
#y=X_data.iloc[:,1].values.tolist()

[5.0, 5.1, 4.4, 5.0, 5.4, 5.0]

In [179]:
for i in range(len(W)):
  print(i)

0
1
2
3


In [180]:
from plotly.subplots import make_subplots

fig= make_subplots(rows=int(len(W)/2), cols=2)

for i in range(len(W)):
  if i%2==0:
    a=i//2
    b=1
  else:
    a=i//2
    b=2
  x_plot=[min(df.iloc[:,0])-0.5, max(df.iloc[:,0])+0.5]
  y_plot=[(-W[i][2]-W[i][0]*j)/W[i][1] for j in x_plot ]
  fig.add_trace( go.Scatter(
        x=x_setosa.iloc[:,0].values.tolist(),
        y=x_setosa.iloc[:,1].values.tolist(),
        mode='markers',marker=dict(
            color='red'),showlegend=False),row=a+1,col=b)
  fig.add_trace( go.Scatter(
        x=x_versicolor.iloc[:,0].values.tolist(),
        y=x_versicolor.iloc[:,1].values.tolist(),
        mode='markers',marker=dict(
            color='blue'),showlegend=False),row=a+1,col=b)
  fig.add_trace(go.Scatter(
        x=x_plot,
        y=y_plot,
        mode="lines",
        name="PCA line",marker=dict(
            color='green')
    ,showlegend=False),row=a+1,col=b)

fig.update_layout(
    autosize=False,
    width=1200,
    height=2000)

HTML(fig.to_html())

Output hidden; open in https://colab.research.google.com to view.

In [192]:
df = px.data.iris().iloc[:100,:]
fig = px.scatter(df, x="sepal_length", y="sepal_width", color="species",template="plotly_dark")
fig.show()
HTML(fig.to_html())

Output hidden; open in https://colab.research.google.com to view.

In [195]:
X_data=px.data.iris().iloc[:100,[0,1]]
Y_data=[y if y==1 else -1 for y in px.data.iris().iloc[:100,-1]]

In [196]:
w,W, error_points= perceptron_learning_algorithm(3,X_data, Y_data,0)

In [198]:
fig = go.Figure()
x_plot=[min(px.data.iris().iloc[:100,0])-0.5, max(px.data.iris().iloc[:100,0])+0.5]
y_plot=[(-w[2]-w[0]*i)/w[1] for i in x_plot ]
fig = px.scatter(df, x="sepal_length", y="sepal_width", color="species",template="plotly_dark")

fig.add_trace(
    go.Scatter(
        x=x_plot,
        y=y_plot,
        mode="lines",
        name="PCA line"
    ))

fig.show()
HTML(fig.to_html())

Output hidden; open in https://colab.research.google.com to view.

In [199]:
fig = go.Figure(data=go.Scatter(x=[i+1 for i in range(len(error_points))], y=error_points))
fig.update_layout(xaxis_title = "epochs", 
                    yaxis_title = "number of misclassifications",template="plotly_dark")
fig.show()
HTML(fig.to_html())

Output hidden; open in https://colab.research.google.com to view.